# Site settings
title: theSoulfulSapien
author: Deepak Nair
email: soulfulsapien@gmail.com
url: https://thesoulfulsapien.github.io
description: >
  A digital garden exploring technology, philosophy, and personal growth

favicon: "./favicon.ico"
show_excerpts: false

# Moving theme settings
remote_theme: huangyz0918/moving

moving:
  avatar_url: "" # Add your avatar URL here
  about_you: I am an amazing person. # short description about you
  date_format: "%b %d"
  back_to: "Home"
  
  # Social links
  social_links:
    github: # your github username
    linkedin: # your linkedin username
    twitter: # your twitter username
    rss: RSS


# Build settings
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
